CREATE TABLE produto (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    codigo VARCHAR(13) NOT NULL
);

CREATE TABLE inventario (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    codigo VARCHAR(6) NOT NULL,
    integrado VARCHAR(1) NOT NULL
);

CREATE TABLE inventario_produtos (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    codigo VARCHAR(6) NOT NULL,
    produto VARCHAR(13) NOT NULL,
    quantidade INTEGER NOT NULL
);